# Generated by Django 6.1.1 on 2026-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_fieldmodel_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fields/'),
        ),
    ]
