# Generated by Django 6.1.1 on 2026-09-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_fieldmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
